*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 01:43:47 2019] ***
compiled with version: 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4) on 14 May 2019 06:35:16
os: Darwin-18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
nodename: joshuaMBP
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES
writing pidfile to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid
detected binary path: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/bin/uwsgi
chdir() to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/
your processes number limit is 709
your memory page size is 4096 bytes
detected max file descriptor number: 10240
building mime-types dictionary from file /etc/apache2/mime.types...1003 entry found
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on localhost:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:52695 (port auto-assigned) fd 3
Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55)  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
Set PythonHome to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7f9a8180e000
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
[uwsgi-cron] command "{ sleep 66 && kill -HUP $(cat /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid) && ls -tp /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/uwsgi-* | grep -v '/$' | tail -n +7  | xargs -d '\n' -r rm --; } &" registered as cron task
mapped 1117336 bytes (1091 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f9a8180e000 pid: 71150 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 71150)
spawned uWSGI worker 1 (pid: 71154, cores: 1)
spawned uWSGI worker 2 (pid: 71155, cores: 1)
spawned uWSGI worker 3 (pid: 71156, cores: 1)
spawned uWSGI worker 4 (pid: 71157, cores: 1)
spawned uWSGI worker 5 (pid: 71158, cores: 1)
spawned uWSGI worker 6 (pid: 71159, cores: 1)
spawned uWSGI worker 7 (pid: 71160, cores: 1)
spawned uWSGI worker 8 (pid: 71161, cores: 1)
spawned uWSGI worker 9 (pid: 71162, cores: 1)
spawned uWSGI worker 10 (pid: 71163, cores: 1)
spawned uWSGI http 1 (pid: 71164)
subprocess 71151 exited with code 0
[2019-08-05 01:43:51,860] Invalid filter: 'has_group'
Traceback (most recent call last):
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: "user|has_group:'Admin'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./runMES/views.py", line 214, in home
    return render(request,'runMES/home.html',{'version':version,'lastupdate':lastupdate,'note':note,'copyright':cp_right,'base':'modeling_base.html'})
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 884, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 887, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 657, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 569, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'has_group'
[2019-08-05 01:43:57,063] Invalid filter: 'has_group'
Traceback (most recent call last):
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: "user|has_group:'Admin'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./runMES/views.py", line 214, in home
    return render(request,'runMES/home.html',{'version':version,'lastupdate':lastupdate,'note':note,'copyright':cp_right,'base':'modeling_base.html'})
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 884, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 887, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 657, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 569, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'has_group'
[2019-08-05 01:44:28,444] Invalid filter: 'has_group'
Traceback (most recent call last):
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: "user|has_group:'Admin'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./runMES/views.py", line 214, in home
    return render(request,'runMES/home.html',{'version':version,'lastupdate':lastupdate,'note':note,'copyright':cp_right,'base':'modeling_base.html'})
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 884, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 887, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 657, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 569, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'has_group'
[2019-08-05 01:44:34,417] Invalid filter: 'has_group'
Traceback (most recent call last):
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: "user|has_group:'Admin'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./runMES/views.py", line 214, in home
    return render(request,'runMES/home.html',{'version':version,'lastupdate':lastupdate,'note':note,'copyright':cp_right,'base':'modeling_base.html'})
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 884, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 887, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 657, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 569, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'has_group'
[2019-08-05 01:44:59,534] Invalid filter: 'has_group'
Traceback (most recent call last):
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: "user|has_group:'Admin'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./runMES/views.py", line 214, in home
    return render(request,'runMES/home.html',{'version':version,'lastupdate':lastupdate,'note':note,'copyright':cp_right,'base':'modeling_base.html'})
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 884, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 887, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 657, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 569, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'has_group'
[2019-08-05 01:45:33,131] {'modeling_view': 'v_name'}
[2019-08-05 01:45:33,139] Invalid filter: 'has_group'
Traceback (most recent call last):
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: "user|has_group:'Admin'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./modeling/views.py", line 26, in modeling_home
    return render(request,'modeling/modeling_home.html',{'version':runMES_view.version,'lastupdate':runMES_view.lastupdate,'note':runMES_view.note,'copyright':runMES_view.cp_right,'base':'modeling_base.html'})
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 884, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 887, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 657, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 569, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'has_group'
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 71164)
worker 10 buried after 1 seconds
worker 9 buried after 1 seconds
worker 8 buried after 1 seconds
worker 7 buried after 1 seconds
worker 6 buried after 1 seconds
worker 5 buried after 1 seconds
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 10:19:22 2019] ***
compiled with version: 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4) on 14 May 2019 06:35:16
os: Darwin-18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
nodename: joshuaMBP
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES
writing pidfile to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid
detected binary path: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/bin/uwsgi
chdir() to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/
your processes number limit is 709
your memory page size is 4096 bytes
detected max file descriptor number: 10240
building mime-types dictionary from file /etc/apache2/mime.types...1003 entry found
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on localhost:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:55155 (port auto-assigned) fd 3
Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55)  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
Set PythonHome to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7fe33300d400
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
[uwsgi-cron] command "{ sleep 66 && kill -HUP $(cat /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid) && ls -tp /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/uwsgi-* | grep -v '/$' | tail -n +7  | xargs -d '\n' -r rm --; } &" registered as cron task
mapped 1117336 bytes (1091 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7fe33300d400 pid: 72355 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 72355)
spawned uWSGI worker 1 (pid: 72359, cores: 1)
spawned uWSGI worker 2 (pid: 72360, cores: 1)
spawned uWSGI worker 3 (pid: 72361, cores: 1)
spawned uWSGI worker 4 (pid: 72362, cores: 1)
spawned uWSGI worker 5 (pid: 72363, cores: 1)
spawned uWSGI worker 6 (pid: 72364, cores: 1)
spawned uWSGI worker 7 (pid: 72365, cores: 1)
spawned uWSGI worker 8 (pid: 72366, cores: 1)
spawned uWSGI worker 9 (pid: 72367, cores: 1)
spawned uWSGI worker 10 (pid: 72368, cores: 1)
spawned uWSGI http 1 (pid: 72369)
subprocess 72356 exited with code 0
[2019-08-05 10:19:31,528] Internal Server Error: /modeling/
Traceback (most recent call last):
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "./modeling/views.py", line 24, in modeling_home
    mylog.info({'modeling_view':'v_name','groups':request.user.groups.valus_list('name',flat=True)})
AttributeError: 'ManyRelatedManager' object has no attribute 'valus_list'
[pid: 72368|app: 0|req: 1/1] 127.0.0.1 () {40 vars in 1196 bytes} [Mon Aug  5 10:19:31 2019] GET /modeling/ => generated 70624 bytes in 263 msecs (HTTP/1.1 500) 5 headers in 168 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 72369)
worker 10 buried after 1 seconds
worker 9 buried after 1 seconds
worker 8 buried after 1 seconds
worker 7 buried after 1 seconds
worker 6 buried after 1 seconds
worker 5 buried after 1 seconds
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 10:19:59 2019] ***
compiled with version: 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4) on 14 May 2019 06:35:16
os: Darwin-18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
nodename: joshuaMBP
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES
writing pidfile to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid
detected binary path: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/bin/uwsgi
chdir() to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/
your processes number limit is 709
your memory page size is 4096 bytes
detected max file descriptor number: 10240
building mime-types dictionary from file /etc/apache2/mime.types...1003 entry found
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on localhost:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:55187 (port auto-assigned) fd 3
Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55)  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
Set PythonHome to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7f97ad802e00
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
[uwsgi-cron] command "{ sleep 66 && kill -HUP $(cat /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid) && ls -tp /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/uwsgi-* | grep -v '/$' | tail -n +7  | xargs -d '\n' -r rm --; } &" registered as cron task
mapped 1117336 bytes (1091 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f97ad802e00 pid: 72376 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 72376)
spawned uWSGI worker 1 (pid: 72380, cores: 1)
spawned uWSGI worker 2 (pid: 72381, cores: 1)
spawned uWSGI worker 3 (pid: 72382, cores: 1)
spawned uWSGI worker 4 (pid: 72383, cores: 1)
spawned uWSGI worker 5 (pid: 72384, cores: 1)
spawned uWSGI worker 6 (pid: 72385, cores: 1)
spawned uWSGI worker 7 (pid: 72386, cores: 1)
spawned uWSGI worker 8 (pid: 72387, cores: 1)
spawned uWSGI worker 9 (pid: 72388, cores: 1)
spawned uWSGI worker 10 (pid: 72389, cores: 1)
spawned uWSGI http 1 (pid: 72390)
subprocess 72377 exited with code 0
[2019-08-05 10:20:03,807] {'modeling_view': 'v_name', 'groups': <QuerySet ['OP', 'Super', 'Manager']>}
[2019-08-05 10:20:03,911] Invalid filter: 'has_group'
Traceback (most recent call last):
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: "user|has_group:'Admin'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./modeling/views.py", line 27, in modeling_home
    return render(request,'modeling/modeling_home.html',{'version':runMES_view.version,'lastupdate':runMES_view.lastupdate,'note':runMES_view.note,'copyright':runMES_view.cp_right,'base':'modeling_base.html'})
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 884, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/defaulttags.py", line 887, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 657, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/lib/python3.6/site-packages/django/template/base.py", line 569, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'has_group'
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 72390)
worker 10 buried after 1 seconds
worker 9 buried after 1 seconds
worker 8 buried after 1 seconds
worker 7 buried after 1 seconds
worker 6 buried after 1 seconds
worker 5 buried after 1 seconds
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 10:24:18 2019] ***
compiled with version: 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4) on 14 May 2019 06:35:16
os: Darwin-18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
nodename: joshuaMBP
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES
writing pidfile to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid
detected binary path: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/bin/uwsgi
chdir() to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/
your processes number limit is 709
your memory page size is 4096 bytes
detected max file descriptor number: 10240
building mime-types dictionary from file /etc/apache2/mime.types...1003 entry found
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on localhost:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:55385 (port auto-assigned) fd 3
Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55)  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
Set PythonHome to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7ff79a80d800
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
[uwsgi-cron] command "{ sleep 66 && kill -HUP $(cat /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid) && ls -tp /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/uwsgi-* | grep -v '/$' | tail -n +7  | xargs -d '\n' -r rm --; } &" registered as cron task
mapped 1117336 bytes (1091 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7ff79a80d800 pid: 72418 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 72418)
spawned uWSGI worker 1 (pid: 72422, cores: 1)
spawned uWSGI worker 2 (pid: 72423, cores: 1)
spawned uWSGI worker 3 (pid: 72424, cores: 1)
spawned uWSGI worker 4 (pid: 72425, cores: 1)
spawned uWSGI worker 5 (pid: 72426, cores: 1)
spawned uWSGI worker 6 (pid: 72427, cores: 1)
spawned uWSGI worker 7 (pid: 72428, cores: 1)
spawned uWSGI worker 8 (pid: 72429, cores: 1)
spawned uWSGI worker 9 (pid: 72430, cores: 1)
spawned uWSGI worker 10 (pid: 72431, cores: 1)
spawned uWSGI http 1 (pid: 72432)
subprocess 72419 exited with code 0
[2019-08-05 10:24:25,610] {'modeling_view': 'v_name', 'groups': <QuerySet ['OP', 'Super', 'Manager']>}
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 72432)
worker 10 buried after 1 seconds
worker 9 buried after 1 seconds
worker 8 buried after 1 seconds
worker 7 buried after 1 seconds
worker 6 buried after 1 seconds
worker 5 buried after 1 seconds
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 11:39:53 2019] ***
compiled with version: 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4) on 14 May 2019 06:35:16
os: Darwin-18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
nodename: joshuaMBP
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES
writing pidfile to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid
detected binary path: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/bin/uwsgi
chdir() to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/
your processes number limit is 709
your memory page size is 4096 bytes
detected max file descriptor number: 10240
building mime-types dictionary from file /etc/apache2/mime.types...1003 entry found
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on localhost:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:51340 (port auto-assigned) fd 3
Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55)  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
Set PythonHome to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7fa492800a00
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
[uwsgi-cron] command "{ sleep 66 && kill -HUP $(cat /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid) && ls -tp /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/uwsgi-* | grep -v '/$' | tail -n +7  | xargs -d '\n' -r rm --; } &" registered as cron task
mapped 1117336 bytes (1091 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7fa492800a00 pid: 73110 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 73110)
spawned uWSGI worker 1 (pid: 73115, cores: 1)
spawned uWSGI worker 2 (pid: 73116, cores: 1)
spawned uWSGI worker 3 (pid: 73117, cores: 1)
spawned uWSGI worker 4 (pid: 73118, cores: 1)
spawned uWSGI worker 5 (pid: 73119, cores: 1)
spawned uWSGI worker 6 (pid: 73120, cores: 1)
spawned uWSGI worker 7 (pid: 73121, cores: 1)
spawned uWSGI worker 8 (pid: 73122, cores: 1)
spawned uWSGI worker 9 (pid: 73123, cores: 1)
spawned uWSGI worker 10 (pid: 73124, cores: 1)
spawned uWSGI http 1 (pid: 73125)
subprocess 73111 exited with code 0
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 73125)
worker 10 buried after 1 seconds
worker 9 buried after 1 seconds
worker 8 buried after 1 seconds
worker 7 buried after 1 seconds
worker 6 buried after 1 seconds
worker 5 buried after 1 seconds
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 11:41:24 2019] ***
compiled with version: 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4) on 14 May 2019 06:35:16
os: Darwin-18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
nodename: joshuaMBP
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES
writing pidfile to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid
detected binary path: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/bin/uwsgi
chdir() to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/
your processes number limit is 709
your memory page size is 4096 bytes
detected max file descriptor number: 10240
building mime-types dictionary from file /etc/apache2/mime.types...1003 entry found
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on localhost:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:51547 (port auto-assigned) fd 3
Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55)  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
Set PythonHome to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7f898f005200
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
[uwsgi-cron] command "{ sleep 66 && kill -HUP $(cat /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid) && ls -tp /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/uwsgi-* | grep -v '/$' | tail -n +7  | xargs -d '\n' -r rm --; } &" registered as cron task
mapped 1117336 bytes (1091 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f898f005200 pid: 73138 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 73138)
spawned uWSGI worker 1 (pid: 73142, cores: 1)
spawned uWSGI worker 2 (pid: 73143, cores: 1)
spawned uWSGI worker 3 (pid: 73144, cores: 1)
spawned uWSGI worker 4 (pid: 73145, cores: 1)
spawned uWSGI worker 5 (pid: 73146, cores: 1)
spawned uWSGI worker 6 (pid: 73147, cores: 1)
spawned uWSGI worker 7 (pid: 73148, cores: 1)
spawned uWSGI worker 8 (pid: 73149, cores: 1)
spawned uWSGI worker 9 (pid: 73150, cores: 1)
spawned uWSGI worker 10 (pid: 73151, cores: 1)
spawned uWSGI http 1 (pid: 73152)
subprocess 73139 exited with code 0
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 73152)
worker 10 buried after 1 seconds
worker 9 buried after 1 seconds
worker 8 buried after 1 seconds
worker 7 buried after 1 seconds
worker 6 buried after 1 seconds
worker 5 buried after 1 seconds
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 11:42:16 2019] ***
compiled with version: 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4) on 14 May 2019 06:35:16
os: Darwin-18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
nodename: joshuaMBP
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES
writing pidfile to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid
detected binary path: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/bin/uwsgi
chdir() to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/
your processes number limit is 709
your memory page size is 4096 bytes
detected max file descriptor number: 10240
building mime-types dictionary from file /etc/apache2/mime.types...1003 entry found
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on localhost:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:51653 (port auto-assigned) fd 3
Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55)  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
Set PythonHome to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7facfd800a00
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
[uwsgi-cron] command "{ sleep 66 && kill -HUP $(cat /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid) && ls -tp /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/uwsgi-* | grep -v '/$' | tail -n +7  | xargs -d '\n' -r rm --; } &" registered as cron task
mapped 1117336 bytes (1091 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7facfd800a00 pid: 73168 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 73168)
spawned uWSGI worker 1 (pid: 73175, cores: 1)
spawned uWSGI worker 2 (pid: 73176, cores: 1)
spawned uWSGI worker 3 (pid: 73177, cores: 1)
spawned uWSGI worker 4 (pid: 73178, cores: 1)
spawned uWSGI worker 5 (pid: 73179, cores: 1)
spawned uWSGI worker 6 (pid: 73180, cores: 1)
spawned uWSGI worker 7 (pid: 73181, cores: 1)
spawned uWSGI worker 8 (pid: 73182, cores: 1)
spawned uWSGI worker 9 (pid: 73183, cores: 1)
spawned uWSGI worker 10 (pid: 73184, cores: 1)
spawned uWSGI http 1 (pid: 73185)
subprocess 73172 exited with code 0
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 73185)
worker 10 buried after 1 seconds
worker 9 buried after 1 seconds
worker 8 buried after 1 seconds
worker 7 buried after 1 seconds
worker 6 buried after 1 seconds
worker 5 buried after 1 seconds
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 11:45:52 2019] ***
compiled with version: 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4) on 14 May 2019 06:35:16
os: Darwin-18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
nodename: joshuaMBP
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES
writing pidfile to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid
detected binary path: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/bin/uwsgi
chdir() to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/
your processes number limit is 709
your memory page size is 4096 bytes
detected max file descriptor number: 10240
building mime-types dictionary from file /etc/apache2/mime.types...1003 entry found
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on localhost:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:52248 (port auto-assigned) fd 3
Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55)  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
Set PythonHome to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7fa49180d400
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
[uwsgi-cron] command "{ sleep 66 && kill -HUP $(cat /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid) && ls -tp /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/uwsgi-* | grep -v '/$' | tail -n +7  | xargs -d '\n' -r rm --; } &" registered as cron task
mapped 1117336 bytes (1091 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7fa49180d400 pid: 73227 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 73227)
spawned uWSGI worker 1 (pid: 73234, cores: 1)
spawned uWSGI worker 2 (pid: 73235, cores: 1)
spawned uWSGI worker 3 (pid: 73236, cores: 1)
spawned uWSGI worker 4 (pid: 73237, cores: 1)
spawned uWSGI worker 5 (pid: 73238, cores: 1)
spawned uWSGI worker 6 (pid: 73239, cores: 1)
spawned uWSGI worker 7 (pid: 73240, cores: 1)
spawned uWSGI worker 8 (pid: 73241, cores: 1)
spawned uWSGI worker 9 (pid: 73242, cores: 1)
spawned uWSGI worker 10 (pid: 73243, cores: 1)
spawned uWSGI http 1 (pid: 73244)
subprocess 73231 exited with code 0
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 73244)
worker 10 buried after 1 seconds
worker 9 buried after 1 seconds
worker 8 buried after 1 seconds
worker 7 buried after 1 seconds
worker 6 buried after 1 seconds
worker 5 buried after 1 seconds
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 11:48:52 2019] ***
compiled with version: 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4) on 14 May 2019 06:35:16
os: Darwin-18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
nodename: joshuaMBP
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES
writing pidfile to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid
detected binary path: /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/bin/uwsgi
chdir() to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/
your processes number limit is 709
your memory page size is 4096 bytes
detected max file descriptor number: 10240
building mime-types dictionary from file /etc/apache2/mime.types...1003 entry found
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on localhost:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:52757 (port auto-assigned) fd 3
Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55)  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
Set PythonHome to /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7ffe85801e00
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
[uwsgi-cron] command "{ sleep 66 && kill -HUP $(cat /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/uwsgi-master.pid) && ls -tp /Users/joshuachin1/Dropbox/workspace/runMES/runMES_1908rc1i/runMES/uwsgi-* | grep -v '/$' | tail -n +7  | xargs -d '\n' -r rm --; } &" registered as cron task
mapped 1117336 bytes (1091 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7ffe85801e00 pid: 73287 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 73287)
spawned uWSGI worker 1 (pid: 73294, cores: 1)
spawned uWSGI worker 2 (pid: 73295, cores: 1)
spawned uWSGI worker 3 (pid: 73296, cores: 1)
spawned uWSGI worker 4 (pid: 73297, cores: 1)
spawned uWSGI worker 5 (pid: 73298, cores: 1)
spawned uWSGI worker 6 (pid: 73299, cores: 1)
spawned uWSGI worker 7 (pid: 73300, cores: 1)
spawned uWSGI worker 8 (pid: 73301, cores: 1)
spawned uWSGI worker 9 (pid: 73302, cores: 1)
spawned uWSGI worker 10 (pid: 73303, cores: 1)
spawned uWSGI http 1 (pid: 73304)
subprocess 73291 exited with code 0
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 73304)
worker 10 buried after 1 seconds
worker 9 buried after 1 seconds
worker 8 buried after 1 seconds
worker 7 buried after 1 seconds
worker 6 buried after 1 seconds
worker 5 buried after 1 seconds
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
